### ISSUE TITLE
Необработанное исключение при неустановленной переменной окружения

### ISSUE THREAD

**Issue by AlphaBeth** [skychik/for-programming#17]
```
Не существует переменной окружения EmployeeFile.
Exception in thread "main" java.io.FileNotFoundException: src\main\java\ru\ifmo\cs\programming\lab5\input.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:70)
Exception in thread "Thread-0" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at ru.ifmo.cs.programming.lab5.App.save(App.java:285)
	at ru.ifmo.cs.programming.lab5.App.lambda$main$0(App.java:64)
	at java.lang.Thread.run(Thread.java:745)
```

Конечному пользователю должно показываться как можно меньше исключений. Данную ситуацию можно корректно обработать.

**Comment by AlphaBeth** [comment]
Из того же разряда.
Не нужно показывать исключения в ситуациях, которые вы уже обработали.
```
ivan@Acer:~/tmp/for-programming/target$ export EmployeeFile=
ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
Указанного файла не существует. 
Exception in thread "main" java.io.FileNotFoundException: src\main\java\ru\ifmo\cs\programming\lab5\input.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:70)
java.io.FileNotFoundException:  (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.PrintWriter.<init>(PrintWriter.java:263)
	at ru.ifmo.cs.programming.lab5.App.save(App.java:286)
	at ru.ifmo.cs.programming.lab5.App.lambda$main$0(App.java:64)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by skychik** [comment]
Вы в какой ветке смотрите?

**Comment by AlphaBeth** [comment]
master

**Comment by skychik** [comment]
withoutStringFilePath
тут чекните

**Comment by AlphaBeth** [comment]
Все равно выводятся страшные стектрейсы.
```
ivan@Acer:~/tmp/for-programming/target$ echo $EmployeeFile 
a.csv
ivan@Acer:~/tmp/for-programming/target$ ls $EmployeeFile 
ls: cannot access 'a.csv': No such file or directory
ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
Exception in thread "main" java.io.FileNotFoundException: Указанного файла не существует. 
	at ru.ifmo.cs.programming.lab5.core.InteractiveModeFunctions.load(InteractiveModeFunctions.java:81)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:39)
```

А здесь даже нет понятного пользователю сообщения об ошибке.
```
ivan@Acer:~/tmp/for-programming/target$ unset EmployeeFile 
ivan@Acer:~/tmp/for-programming/target$ echo $EmployeeFile 

ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at ru.ifmo.cs.programming.lab5.core.InteractiveModeFunctions.<clinit>(InteractiveModeFunctions.java:17)
```

**Comment by skychik** [comment]
Чем стактрейсы страшны?)

**Comment by AlphaBeth** [comment]
Тем, что они понятны только программисту. Для пользователя это будет сигналом, что что-то сломалось. Они скрывают полезную информацию от взгляда пользователя - ваше сообщение об ошибке, которое несет смысл и руководство к ее исправлению, теряется за огромным стектрейсом.

**Comment by skychik** [comment]
ok

**Comment by skychik** [comment]
поправлено

**Comment by AlphaBeth** [comment]
```
ivan@Acer:~/Documents/code/for-programming/target$ unset EmployeeFile 
ivan@Acer:~/Documents/code/for-programming/target$ java -jar dict.jar 
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:31)

```
Не, не работает. 71e33325fc0b0cee75d10fede585e7b8cd11060a

**Comment by skychik** [comment]
Сор, поправил
