### ISSUE TITLE
Необработанное исключение при пустом файле

### ISSUE THREAD

**Issue by AlphaBeth** [skychik/for-programming#18]
Почему у вас запрещено использование пустых файлов, и возникающая при их использовании ошибка неинформативна? Отсутствуют внятные сообщения, просто возникает непонятное исключение.

```
ivan@Acer:~/tmp/for-programming/target$ export EmployeeFile=a.csv
ivan@Acer:~/tmp/for-programming/target$ touch a.csv
ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
[]
Exception in thread "main" java.io.FileNotFoundException: src\main\java\ru\ifmo\cs\programming\lab5\input.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:70)
java.io.PrintWriter@15ee78dc
```

**Comment by skychik** [comment]
Перепроверьте в другой ветке

**Comment by AlphaBeth** [comment]
Да, с пустым файлом начало работать, но вот при некорректных данных...
```
ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
Приложение не обрабатывает указанный в строке 1 класс.
Exception in thread "main" java.lang.NullPointerException
	at java.util.ArrayDeque.addLast(ArrayDeque.java:244)
	at java.util.ArrayDeque.add(ArrayDeque.java:418)
	at ru.ifmo.cs.programming.lab5.core.InteractiveModeFunctions.load(InteractiveModeFunctions.java:88)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:39)
ivan@Acer:~/tmp/for-programming/target$ cat a.csv
sd;lfk
sadlfkj
asl;dkfj
ivan@Acer:~/tmp/for-programming/target$ git status 
On branch withoutStringFilePath
Your branch is up-to-date with 'origin/withoutStringFilePath'.
nothing to commit, working directory clean
```

**Comment by skychik** [comment]
поправлено

**Comment by AlphaBeth** [comment]
Подсказка по работе с гитхабом: вы можете в комментарии к коммиту добавлять сообщения вроде `Close #18`, и тогда при слиянии ветки с мастером соответствующий issue будет закрыт.
Чуть подробнее [здесь](https://help.github.com/articles/closing-issues-via-commit-messages/).
