### ISSUE TITLE
"Указанного файла не существует", хотя он есть

### ISSUE THREAD

**Issue by AlphaBeth** [skychik/for-programming#19]
```
ivan@Acer:~/tmp/for-programming/target$ echo $EmployeeFile 
a.csv
ivan@Acer:~/tmp/for-programming/target$ ls -l $EmployeeFile 
---------- 1 ivan ivan 0 апр  2 16:36 a.csv
ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
Указанного файла не существует. 
Exception in thread "main" java.io.FileNotFoundException: src\main\java\ru\ifmo\cs\programming\lab5\input.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:70)
java.io.FileNotFoundException: a.csv (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.PrintWriter.<init>(PrintWriter.java:263)
	at ru.ifmo.cs.programming.lab5.App.save(App.java:286)
	at ru.ifmo.cs.programming.lab5.App.lambda$main$0(App.java:64)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by skychik** [comment]
Сложно.

**Comment by AlphaBeth** [comment]
У вас же были основы работы с UNIX-like операционными системами в курсе ОВТ.
Суть ошибки в том, что файл существует, но нет прав на его чтение и запись.
Проверил и в другой ветке, в ней это тоже актуально.
```
ivan@Acer:~/tmp/for-programming/target$ echo $EmployeeFile 
a.csv
ivan@Acer:~/tmp/for-programming/target$ touch $EmployeeFile 
ivan@Acer:~/tmp/for-programming/target$ chmod 0 $EmployeeFile 
ivan@Acer:~/tmp/for-programming/target$ ls -l $EmployeeFile 
---------- 1 ivan ivan 0 апр  2 17:36 a.csv
ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
Exception in thread "main" java.io.FileNotFoundException: Указанного файла не существует. 
	at ru.ifmo.cs.programming.lab5.core.InteractiveModeFunctions.load(InteractiveModeFunctions.java:81)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:39)
ivan@Acer:~/tmp/for-programming/target$ git status 
On branch withoutStringFilePath
Your branch is up-to-date with 'origin/withoutStringFilePath'.
nothing to commit, working directory clean
```

**Comment by skychik** [comment]
проблема понята

**Comment by skychik** [comment]
вроде поправили
