### ISSUE TITLE
Exception in thread "main" java.util.NoSuchElementException

### ISSUE THREAD

**Issue by AlphaBeth** [skychik/for-programming#21]
Исключение неизвестного происхождения.
Шаги для воспроизведения:
```
ivan@Acer:~/tmp/for-programming/target$ wc $EmployeeFile 
0 0 0 a.csv
ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
Состояние очереди после считывания:

Write your command:
^Cjava.io.PrintWriter@766a608
ivan@Acer:~/tmp/for-programming/target$ echo '' > $EmployeeFile 
ivan@Acer:~/tmp/for-programming/target$ wc $EmployeeFile 
1 0 1 a.csv
ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at ru.ifmo.cs.programming.lab5.domain.Employee.parseEmployee(Employee.java:161)
	at ru.ifmo.cs.programming.lab5.core.InteractiveModeFunctions.load(InteractiveModeFunctions.java:87)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:39)
ivan@Acer:~/tmp/for-programming/target$ git status 
On branch withoutStringFilePath
Your branch is up-to-date with 'origin/withoutStringFilePath'.
nothing to commit, working directory clean
```

**Comment by skychik** [comment]
Сложно.

**Comment by skychik** [comment]
вроде поправили
