### ISSUE TITLE
^D рушит программу

### ISSUE THREAD

**Issue by AlphaBeth** [skychik/for-programming#22]
```
ivan@Acer:~/tmp/for-programming/target$ java -jar dict.jar 
Состояние очереди после считывания:

Write your command:
sd
Write your command:
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at ru.ifmo.cs.programming.lab5.App.interactiveMode(App.java:62)
	at ru.ifmo.cs.programming.lab5.App.main(App.java:51)
java.io.PrintWriter@766a608
```

**Comment by skychik** [comment]
^D - это не цифра или что?

**Comment by AlphaBeth** [comment]
Сочетание клавиш Ctrl+D.
